### ISSUE TITLE
vector store not working properly with orderby clause

### ISSUE THREAD

**Issue by affan00733** [georgia-tech-db/evadb#879] opened 2023-06-18 09:39 UTC
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### EVA DB Component

Other

### Bug

- when performing the similarity based query on vector that is creating a vector store from the table features by FAISS and QDRANT, it seems to be corrupted as when locally reading the entire vector store of 2 pdfs it is returning 517

<img width="954" alt="image" src="https://github.com/georgia-tech-db/eva/assets/42251896/5b598416-d48c-4ae7-866f-edd753319c83">

### Minimal Reproducible Example

`import faiss
index = faiss.read_index("/Users/afaanansari/Desktop/gtech/eva/tutorials/evadb_data/index/FAISS_faiss_indexs.index")
index.ntotal`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by jiashenC** [comment] 2023-06-26 05:40
Can you provide detailed steps to reproduce this error? Not sure if this is related to order by desc, but https://github.com/georgia-tech-db/eva/pull/898 tests desc works fine.

**Comment by jiashenC** [comment] 2023-06-26 06:51
Error can be reproduced through `tutorials/privategpt` notebook.

* Answers are not ordered correctly.
* Limit clause not working.

**Comment by jiashenC** [comment] 2023-06-26 17:41
The root cause is different paragraphs in from the same PDF are assigned to the same `_row_id`. Is this PR https://github.com/georgia-tech-db/eva/pull/868 intended to address this issue? @gaurav274

**Comment by gaurav274** [comment] 2023-07-01 17:07
Nice catch. Yes, we need to improve the support of creating indexes directly on unstructured tables.

**Comment by xzdandy** [comment] 2023-09-22 06:20
I think the issue `different paragraphs in from the same PDF are assigned to the same _row_id.` this has been already addressed.

**Closed by xzdandy** 2023-09-22 06:20 UTC
